"""Constants for video frame extraction algorithms."""

REVIEW_TARGET_FRAMES = 50
REVIEW_FRAME_QUALITY = 70

SCENE_SCAN_INTERVAL = 0.5
SCENE_SETTLE_THRESHOLD = 0.01
MIN_NON_BLANK_FRAME_STD = 2.0
HIGH_SSIM_THRESHOLD = 0.99

# Brightness-peaks settings (manual inspection algorithm)
BRIGHTNESS_SCAN_INTERVAL = 1.0
LIGHTNESS_LUMA_BLACK_THRESHOLD = 16
NON_BLACK_MAX_RATIO = 0.98
BRIGHTNESS_DEDUP_SSIM_THRESHOLD = 0.50
